### ISSUE TITLE
Stream Page Layout

### ISSUE THREAD

**Issue by The-Faulty** [LTXland/LTX#5]
Below the streams will be a row of buttons consisting of a channel's name and profile picture. If that channel has any active livestreams, there should be an indicator next to their name, such as a red dot. When you click on the channel button, the streams grey out and you can click on one of the grid slots to make it host that channel's stream. Channels with multiple livestreams would have an element that shows the thumbnails and names of their current streams for the user to pick. All the way at the right of this bar would be a place for the user to enter their own link for livestreams. Also, grid elements should have a button that can be used to swap the stream with the center element.

**Comment by jordanreger** [comment]
Here's a mockup of what I think would work well. The live button will be based on #10 and will disappear if there isn't a current event, shifting all the channels over.
![streams-4](https://user-images.githubusercontent.com/33134197/159944141-d3ca5c25-d336-4782-b6b7-c9f96bc2c0b0.png)
